$(document).ready(
        function(){
            $('div.tmpBind').bind(
                    'mouseover',
                    function(){
                        $(this).find('div').addClass('tmpExampleOver');
                    }
                    );
            $('div.tmpBind').bind(
                    'mouseout',
                    function(){
                        $(this).find('div').removeClass('tmpExampleOver');
                    }
                    );
            $('div.tmpBind').bind(
                    'click',
                    function(){
                        if(!$(this).find('div').hasClass('tmpExampleOn')){
                            $(this).find('div').addClass('tmpExampleOn');
                        }
                        else{
                            $(this).find('div').removeClass('tmpExampleOn');
                        }
                    }
                     );

            $('div.tmpIndividual').mouseover(
                    function(){
                        $(this).find('div').addClass('tmpExampleOver');
                    }
                    ).mouseout(
                    function(){
                        $(this).find('div').removeClass('tmpExampleOver');
                    }
                    ).click(
                    function(){
                        if(!$(this).find('div').hasClass('tmpExampleOn')){
                            $(this).find('div').addClass('tmpExampleOn');
                        }
                        else
                        {
                            $(this).find('div').removeClass('tmpExampleOn');
                        }
                    }
                   );
             $('div.tmpPattern').hover(
                     function(){
                         $(this).find('div').addClass('tmpExampleOver');
                     },
                     function(){
                         $(this).find('div').removeClass('tmpExampleOver');
                                 }
                      ).click(
                          function(){
                              if(!$(this).find('div').hasClass('tmpExampleOn')){
                                  $(this).find('div').addClass('tmpExampleOn');
                              }
                              else
                              {
                                  $(this).find('div').removeClass('tmpExampleOn');
                              }
                          }
                    );

             $('div.tmpTrigger textarea').focus(
                     function($e){
                         $(this).addClass('tmpFocused');
                     }
                 ).blur(
                     function(){
                         $(this).removeClass('tmpFocused');
                     }
                 );
            $('div.tmpTrigger textarea').focus();
                    }
                    );
